language: python
sudo: required
services:
  - docker

jobs:
  include:
    - arch: amd64
      dist: focal
    - arch: arm64-graviton2
      group: edge
      virt: vm
      dist: focal

before_install:
  - docker build -t journald-2-cloudwatch -f Dockerfile .
install:
  - pip install coverage
  - docker build -t journald-2-cloudwatch-test -f Dockerfile.test .

script:
  - docker run --rm -v `pwd`:`pwd` -w `pwd` journald-2-cloudwatch-test

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
