FROM journald-2-cloudwatch

RUN pip install moto coverage
RUN ["/bin/bash", "-c", "echo '[run]\ndata_file=/coverage/.coverage' > /.coveragerc"]
COPY tests /tests
ENTRYPOINT ["coverage", "run", "--source=main", "-m", "unittest"]
